### ISSUE TITLE
Fehlermeldung bei alten Projekten

### ISSUE THREAD

**Issue by Loscho19** [feinheit/fh-fablib#16]
Hey @matthiask

Haben wir ein Vorgehen, wenn dieser Fehler auftritt?

Traceback (most recent call last):
  File "/Users/Fabian/.local/bin/fl", line 8, in <module>
    sys.exit(program.run())
             ^^^^^^^^^^^^^
  File "/Users/Fabian/.local/pipx/venvs/fh-fablib/lib/python3.11/site-packages/invoke/program.py", line 373, in run
    self.parse_collection()
  File "/Users/Fabian/.local/pipx/venvs/fh-fablib/lib/python3.11/site-packages/invoke/program.py", line 465, in parse_collection
    self.load_collection()
  File "/Users/Fabian/.local/pipx/venvs/fh-fablib/lib/python3.11/site-packages/fabric/main.py", line 87, in load_collection
    super(Fab, self).load_collection()
  File "/Users/Fabian/.local/pipx/venvs/fh-fablib/lib/python3.11/site-packages/invoke/program.py", line 699, in load_collection
    module, parent = loader.load(coll_name)
                     ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/Fabian/.local/pipx/venvs/fh-fablib/lib/python3.11/site-packages/invoke/loader.py", line 76, in load
    module = imp.load_module(name, fd, path, desc)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/python@3.11/3.11.4_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/imp.py", line 235, in load_module
    return load_source(name, filename, file)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/python@3.11/3.11.4_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/imp.py", line 172, in load_source
    module = _load(spec)
             ^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 721, in _load
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Users/Fabian/Work/swissfoodresearch.ch/fabfile.py", line 3, in <module>
    import fh_fablib as fl
  File "/Users/Fabian/.local/pipx/venvs/fh-fablib/lib/python3.11/site-packages/fh_fablib/__init__.py", line 218, in <module>
    @task(auto_shortflags=False, help={"force": "Overwrite existing pre-commit files"})
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/Fabian/.local/pipx/venvs/fh-fablib/lib/python3.11/site-packages/invoke/tasks.py", line 357, in inner
    obj = klass(
          ^^^^^^
  File "/Users/Fabian/.local/pipx/venvs/fh-fablib/lib/python3.11/site-packages/fabric/tasks.py", line 21, in __init__
    super(Task, self).__init__(*args, **kwargs)
  File "/Users/Fabian/.local/pipx/venvs/fh-fablib/lib/python3.11/site-packages/invoke/tasks.py", line 76, in __init__
    self.positional = self.fill_implicit_positionals(positional)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/Fabian/.local/pipx/venvs/fh-fablib/lib/python3.11/site-packages/invoke/tasks.py", line 167, in fill_implicit_positionals
    args, spec_dict = self.argspec(self.body)
                      ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/Fabian/.local/pipx/venvs/fh-fablib/lib/python3.11/site-packages/invoke/tasks.py", line 153, in argspec
    spec = inspect.getargspec(func)
           ^^^^^^^^^^^^^^^^^^
AttributeError: module 'inspect' has no attribute 'getargspec'. Did you mean: 'getargs'?

cc: @fabiangermann

**Comment by matthiask** [comment]
Mach sonst mal `~/.local/pipx/venvs/fh-fablib/bin/python -m pip freeze` , wahrscheinlich hast Du eine `invoke` Version vor 2.0 installiert oder so?

`pipx reinstall fh-fablib` hilft allenfalls.

**Comment by matthiask** [comment]
Diese Kombi müsste funktionieren:
```
[12.07. 11:35:10] ~/projects/sites/fh-campaign-sites$ ~/.local/pipx/venvs/fh-fablib/bin/python -m pip freeze
bcrypt==4.0.1
cffi==1.15.1
cryptography==41.0.2
decorator==5.1.1
fabric==3.1.0
fh-fablib @ file:///home/matthias/projects/fh-fablib
invoke==2.1.3
paramiko==3.2.0
pycparser==2.21
PyNaCl==1.5.0
speckenv==4.0
```

**Comment by matthiask** [comment]
`pipx inject` wird offenbar gespeichert, und bei einem `pipx reinstall` nicht gelöscht. `pipx uninject` hilft.
